# Generated by Django 3.2.5 on 2022-03-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_sale_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='id_number',
            new_name='personal_id',
        ),
    ]
