# Generated by Django 3.2.5 on 2022-03-02 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('sales', '0003_rename_id_number_client_personal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='sales.paymentmethod'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
