# Generated by Django 3.2.5 on 2022-03-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20220302_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='currency',
            field=models.CharField(default='', max_length=3),
        ),
    ]
