# Generated by Django 3.2.5 on 2022-03-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id_number',
            field=models.IntegerField(default='0', unique=True),
        ),
    ]
