# Generated by Django 3.2.5 on 2022-03-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_id_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='id_number',
            new_name='personal_id',
        ),
    ]
